/* tslint:disable */
/* eslint-disable */
/**
 * Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PropertyType,
    PropertyTypeFromJSON,
    PropertyTypeFromJSONTyped,
    PropertyTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface ModelWithNullableObjectProperty
 */
export interface ModelWithNullableObjectProperty {
    /**
     * 
     * @type {null | PropertyType}
     * @memberof ModelWithNullableObjectProperty
     */
    propertyName31?: null | PropertyType | null;
}


export function ModelWithNullableObjectPropertyFromJSON(json: any): ModelWithNullableObjectProperty {
    return ModelWithNullableObjectPropertyFromJSONTyped(json, false);
}

export function ModelWithNullableObjectPropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelWithNullableObjectProperty {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'propertyName31': !exists(json, 'propertyName31') ? undefined : null | PropertyTypeFromJSON(json['propertyName31']),
    };
}

export function ModelWithNullableObjectPropertyToJSON(value?: ModelWithNullableObjectProperty | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'propertyName31': null | PropertyTypeToJSON(value.propertyName31),
    };
}

