generatorName: typescript-fetch
outputDir: samples/client/petstore/typescript-fetch/builds/nullable-object-property
inputSpec: modules/openapi-generator/src/test/resources/3_0/nullable-object-property.yaml
templateDir: modules/openapi-generator/src/main/resources/typescript-fetch
